spring:
  application:
    name: "BookingApp"
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
QVNDQktnd2dnU2tBZ0VBQW9JQkFRQytKUFJQWmVyRWdnZE4KdHdORlp1cjF1TWk5RjlIVE9nYkVC
WE5abVhQNGRoMENOdUd0UHdCdkl2Sm5mMEJ1RFJSeG4yNnoxNUMzV3F1Swp5RjJMdnUzNk9nMTJG
bFl3NU9XVGRLYWh5L1BtbXBEZnFpM3k0ZkVRSktGZ25Kc1R0c1lNQnA1djZ5d0FTUFFZCmo4YjJt
dTVXN0lxOWdvTUhqcnVzWSsrSExDWDR5OHI0VDhKWndMOGkrWVZNMlR4a3lkaG5MWjdPN2xDVjhx
cmMKbUpnZGh5U2lWUzJjenRjRFIvNEdJbzQ1Zm5xTGRLd3BuY2h6SlgrcDZDa3lHN0hnQTQwcXFj
RjF1UTQyRG13cwp0SlRxS1lzckdFclBQTHk0cjVldnVLUHZNQm1EY3dvU2tRZjlMa3BsZWJlNXNJ
VVlnSUtLVjBNaHNPYlNiYURTCnFYS1U0QS8xQWdNQkFBRUNnZ0VBU0tWM3ppb0RNMGIyb1dPTjFX
TkgyOC9ZcWg1Q3BYQWpDNXVGZ2JNV1V0UlYKcXZYcTdUVUg1bTQwclFRNlNwR213TzZIN2lBckEx
S1ovYkVseEhHVEhLbzNZR21TVHFYMWJJd0I2Z2t4UzJhOAplU2ZjM0ZJa3R1VTMzdUNXZzBhdWpn
T3RYdGM3L1hQaUJzeFAyUUpDazJWV2NLYy9ocENxOVdkTktaamRmUnMrCm95amFTcVczRnk1c3Y0
QmpGRGxXVzB4OWJoQTdpYWJYaVRSdXJibDhNOSt4VVBvdVMwQnpUYXV4TzAxL2MzNVEKZ0JSQjFj
aXdFY1lJcHZpdFZDU0lsV1NwbzJadXVsVmk2NitxUUxYRzlBTmV2Z3pmeldQU3E4c0VpU2ZkcU9E
YQpCQytqb2V2Q2pUd0V6ZnN1cXZFNDFtUEtNV3Zpems3R05uZmRNM2NUUVFLQmdRRHJoSmNneHcv
WVY4VmxvLzNVClZaU0toTzJhbG9kREt0UkphNlRrdDZCYk9zYStOYW1ITlp3TFpZNUpKVFQ3OFdB
VUtGMnZGZmlBelpkWGRteWkKSTV2M1hTS2t5MEFVWFAvY3ZYdERvOGc5dC9HN3oxVnJXWE8ycktJ
dkJBVVRYc2dlY1ZLcmlqSmZkeFJoMU8rMwpKdGErYkd3Q2ZUSCtNcGZ6dVJoSmZzdGhCUUtCZ1FE
T3JqS2hUL0xISEVrSVZ0dlp0Q1lJcG5ZZFhhYjNqNE10CmVNM3A4N1VaUFk2YlpuOGQ5T3ltYlJu
amtwRXRpUlNLN3p6emNVcVY0Qlpha21BVDNrbmQzTm5pdElNSS9mbUoKZTd0dDZ6dDh1bHVhZkxa
bHRIY2xxNlVFZTZQWDd1Skk1S3k3U3J6NVByWE1ZK3VHTGh2ZVpZclFOTjVtSko1agpzRTlGRmlq
bU1RS0JnUUNPSWd1T3BYT2pqWHk4bFZaM1VWcCtxakEycmdkZGVyaDR3clRWcnhmZ1ZyMWdSMFJU
CkxBQkxSSE8xSXZZeDRmNm95NStXTFgwMlJsekNWTjdFanhidUZzLzBnaERlK1MwVWkybWJiWGxI
L2YydDZUZFUKdkx3L2p6bWxoQmlJRXhoVWZ2RjBRc2VabzJTeWtlNUZLdlJJSVdpaHErcUN6UWUw
OTR4M3RrU0kvUUtCZ1FDWAo5SXRVL3FySXFZc29qblBsaEFYU3BsQ0JGcklEb1lnWWpwRVdTUkFG
RnJVYW5Da3BwVUc0dXM0bCswU3g3ZThrCmx2Q0JLL0ppYnZjQWNFNGpUWE9Sb3lhdS8zaTN5OE1E
eWV6cnk5OVl2TXRNc2hTSWdqNTNlOU0va0lmTjR0eU0KSzFTei95Y2hPWElBYkJabCtOQ1VtcU9N
b05KQzF2bDg0Y3ZtUjN5YWdRS0JnRWJUY0ZMdVVpRVVVSzZuSjQ2eQpFdHRreVdnS1JPZXJGV21w
NDlkajBTdVlCRkhOWTlKV1d5OGUzVFlnNE9RNENEa3RLUllDRkMvb2pxOUxOV2NiCjVsU2c1SnRW
UUFGaENQam9oNXhLaURadDMrM0N0cE8zZnVGaUt5ZFpRWHVaUmhuOG54UkM1OVJFWFpGTXhSaXIK
NkNmT0tDMG1FeGp2QW43YkRzTncyNkRECi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVYekNDQXNlZ0F3SUJBZ0lSQUsxNHErQytB
R0pDcFhUMy9UWFpRSFV3RFFZSktvWklodmNOQVFFTEJRQXcKZ1pFeEhqQWNCZ05WQkFvVEZXMXJZ
MlZ5ZENCa1pYWmxiRzl3YldWdWRDQkRRVEV6TURFR0ExVUVDd3dxWm5KaApibU5sYkdsdVpTMXVa
MjlBYUhBdGNISnZZbTl2YXlBb1JuSmhibU5sYkdsdVpTQk9SMDhwTVRvd09BWURWUVFECkRERnRh
Mk5sY25RZ1puSmhibU5sYkdsdVpTMXVaMjlBYUhBdGNISnZZbTl2YXlBb1JuSmhibU5sYkdsdVpT
Qk8KUjA4cE1CNFhEVEkxTURNeU1ERXpOVGsxTVZvWERUSTNNRFl5TURFeU5UazFNVm93WGpFbk1D
VUdBMVVFQ2hNZQpiV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJR05sY25ScFptbGpZWFJsTVRNd01R
WURWUVFMRENwbWNtRnVZMlZzCmFXNWxMVzVuYjBCb2NDMXdjbTlpYjI5cklDaEdjbUZ1WTJWc2FX
NWxJRTVIVHlrd2dnRWlNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDK0pQ
UlBaZXJFZ2dkTnR3TkZadXIxdU1pOUY5SFRPZ2JFQlhOWgptWFA0ZGgwQ051R3RQd0J2SXZKbmYw
QnVEUlJ4bjI2ejE1QzNXcXVLeUYyTHZ1MzZPZzEyRmxZdzVPV1RkS2FoCnkvUG1tcERmcWkzeTRm
RVFKS0ZnbkpzVHRzWU1CcDV2Nnl3QVNQUVlqOGIybXU1VzdJcTlnb01IanJ1c1krK0gKTENYNHk4
cjRUOEpad0w4aStZVk0yVHhreWRobkxaN083bENWOHFyY21KZ2RoeVNpVlMyY3p0Y0RSLzRHSW80
NQpmbnFMZEt3cG5jaHpKWCtwNkNreUc3SGdBNDBxcWNGMXVRNDJEbXdzdEpUcUtZc3JHRXJQUEx5
NHI1ZXZ1S1B2Ck1CbURjd29Ta1FmOUxrcGxlYmU1c0lVWWdJS0tWME1oc09iU2JhRFNxWEtVNEEv
MUFnTUJBQUdqWkRCaU1BNEcKQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdF
RkJRY0RBVEFmQmdOVkhTTUVHREFXZ0JSVQpyN09QRWVMa2UxZ1BKQ3E1eVZEZlNFb0lZREFhQmdO
VkhSRUVFekFSZ2c5c2IyTmhiQzR3ZUdSaVpTNWtaWFl3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dH
QkFDbERuanVtYnpiV3BTWXNHNXUzcFdSV2xXY29wbTVTUGpuUXUyZjYKLzlLRW1kTERTc0pRdXFt
RmJESit2VTJDemZBUy9MNEJMcnhYdll6TEEwWGY2U3g4UUJnWmJ2dzR5a0cwWVhJagovQ082anJK
RzBsSXNGUWJGQVZ6L2wzRDZ4K0tjV1BWSEFTdFZrb2NEa05VRjlyR2hwWGlKQnl3UW9STEhJSm95
Ckw2TjU4Y3F6eEw1SVp4eWJOc2pweGhMVEwxeVdjamw0SVMrRXJmaWN0YklFSGp3NWtwb2lTYnJ3
by9GNmkwVncKSVZSdFZMRUFXNmx3RWxTN0FHc0c1bUQvRE5BaFVvbWxTaWtvUUhCU1oxTC9xcHI0
aE5ibEJHNGRzVlo2MzNpSwpOdDhPZnZaUlR2WUE4Ti9FVFVKcVh6Rm56QmZ1Z3B4ZE5vR2R3N3k3
OTFmdm5NaUlLTFZkM3RxZnNTdS80bk9VCk9PN0pVNWc0WjVZWjBhQ0FSeU1taXlVNDg5dnlXak02
VjB3Wm5WdndwVU9GdTRWZHYwZng2cERLa0RZOEd5em0KM1EwU21Vd1V0OGFsZmprajZHZjlVQ3Ey
N2JiM3B4cUwwU1FtY3lOVFZSZG9VUDd5RVB5Y2I1S2tROFE5Z0ErTQpwN3FnajRjREErRWFzVk1m
YlFOOHVFWlJhUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU5RENDQTF5Z0F3SUJBZ0lSQU1iRmY2S0s4
bUZ6RVBYTmVKeW5Rdnd3RFFZSktvWklodmNOQVFFTEJRQXcKZ1pFeEhqQWNCZ05WQkFvVEZXMXJZ
MlZ5ZENCa1pYWmxiRzl3YldWdWRDQkRRVEV6TURFR0ExVUVDd3dxWm5KaApibU5sYkdsdVpTMXVa
MjlBYUhBdGNISnZZbTl2YXlBb1JuSmhibU5sYkdsdVpTQk9SMDhwTVRvd09BWURWUVFECkRERnRh
Mk5sY25RZ1puSmhibU5sYkdsdVpTMXVaMjlBYUhBdGNISnZZbTl2YXlBb1JuSmhibU5sYkdsdVpT
Qk8KUjA4cE1CNFhEVEkxTURNeU1ERXpOVGt5TmxvWERUTTFNRE15TURFek5Ua3lObG93Z1pFeEhq
QWNCZ05WQkFvVApGVzFyWTJWeWRDQmtaWFpsYkc5d2JXVnVkQ0JEUVRFek1ERUdBMVVFQ3d3cVpu
SmhibU5sYkdsdVpTMXVaMjlBCmFIQXRjSEp2WW05dmF5QW9SbkpoYm1ObGJHbHVaU0JPUjA4cE1U
b3dPQVlEVlFRRERERnRhMk5sY25RZ1puSmgKYm1ObGJHbHVaUzF1WjI5QWFIQXRjSEp2WW05dmF5
QW9SbkpoYm1ObGJHbHVaU0JPUjA4cE1JSUJvakFOQmdrcQpoa2lHOXcwQkFRRUZBQU9DQVk4QU1J
SUJpZ0tDQVlFQTF3Nkdad2FFV3FjRHo0STU2UGN1c2xLSDM4NnNTR0hCCnBSNHhwUmh2NDhoZmg1
WGh4eTY3NnpSRFdPNUFGdzBkRXAwVytkcXU4eEU2RjBoUmpzTDJzenJIaUFSK3poT3QKSmFnUjNI
TDljVGx0WHgrZmt6YWRzc0hqK0hPM2dJTmZyWndTY2Y4aTZacDlISUJ0MjkzdHVZck1IdzJtTUh6
VwpzU3dITS9PcDlQZ0NjeStEZUtvSnJHWUtiZWloWkJaOFJVYkFyd1FOaVliLytCVndDbk53QnJv
YWIvU2YrZURFCkRacURWSDE5L0dGak9zODNZZFdlUjErQ2EwNUl5bnBHRTFyckRuZUY0eVJncU0y
WmsvZmZ3NHl4YW5sOUZFYm4KRUxuTCtyRDlGWlZpVUp2eW8wTUNtRG5CSlA1YWYwTS9MT1JHL01y
OEx2dDEwOXdja1hER2tleGFSQzZyQm5nNApFZmZMZHRwN2t6MnFUWjI5bXk2TTlVRU9icWpidHFQ
bzVUYnE0TStWMkhTcVRzVDRDSjV6K2w3ZnovMGwzK01nCngxNU9xQkxrdGlnZGo3aVlteitodHpx
bG9DMzJUV0JxZnhaOUdKTXpLU2Zic2hIaTE2ZFBrOUQreUEvRTBkSUEKRDdad3ZEcUh3V3FBMGRh
RTRhclVPelU2d0tJZk1uMWpBZ01CQUFHalJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQwpCREFTQmdO
VkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJSVXI3T1BFZUxrZTFnUEpDcTV5VkRm
ClNFb0lZREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBcFNZQjEvcFo5RitCQWJYQXVKSmtxcWpV
ZGdrcFVCVTAKYUFrNDJHRHlBbnJQcDNxSjFDYi84QUJuaTBaQXhCeVE1Vlp2MVlJU3FZN3ZuUCs4
NnlzZ3k2RHZhWXVMbWxEVwpOeGVWUnYzTzdHTkdYd2hPZTFUWDJtdlFJOEhBOWc5ci9kUUN0MDJv
d2hkVUlhbnNDNmpPVndTU2RQWENodDFPCkpsRnIwTHF5N09xVVF6Rnc0UXUvWStUYVl4cU1JM3dQ
RlRxakozWDRTSTZtUEFFUHRUV2tTVGxtTTFTR0JoNUEKOVRSclRXOTUwcEMrQVlRY01oTWs5OVNK
OUNYODNPVUMvaGdBNUI3UTlqdE8yZzlJWGd5eDgzdnp1UzJsRGt1YwptK05sT2FMcFZtVWNvamMx
WUF5cXdxOGlCNStPVUVFRmM1SlN4bjJTSGQvTGV4SisyYURJTXhDUCt6V214MHFzClZyK1YrdTFM
RVFVdWZpWUVsMmpFV0F1dCtQTUovcnJzQ3RJOXpDbXVtS011YmppNngwdlJReUhTdGowYWNId2QK
dWVIVm01bjB3VWlPbXJ0Mnh1VjZiajNCNjVHUVM4RDhTME9IQ1kzZkpqa1NYZ1RnYkhRVks1Q05w
dWF0NlNJRwpuc3JHZVZRREs5SzZIL3JmSkhGREJ1djRNbHdsbzhBbwotLS0tLUVORCBDRVJUSUZJ
Q0FURS0tLS0tCg==""

server:
  port: 8443
  ssl:
    enabled: true
    bundle: web