name: security-pipeline

on:
  workflow_dispatch: # Manual trigger for testing

jobs:
  osv-scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.0.2"
    with:
      scan-args: |-
        ./app --format json --output reports/osv-results.sarif
    permissions:
      security-events: write

  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run Semgrep Analysis
        run: |
          mkdir -p reports
          semgrep --config=p/java --output=reports/semgrep-results.sarif --sarif .
      
      - name: Upload Semgrep Report to Security Dashboard
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/semgrep-results.sarif