name: security-pipeline

permissions:
  actions: read
  contents: read
  security-events: write

on:
  workflow_dispatch: # Manual trigger for testing

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@main
        with:
          scan-args: |-
            --lockfile=app/gradle.lockfile
            --format=sarif
            --output=osv-results.sarif
      
      - name: Upload OSV Scanner results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif

  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run Semgrep Analysis
        run: |
          mkdir -p reports
          semgrep --config=p/java --output=semgrep-results.sarif --sarif .
      
      - name: Upload Semgrep Report to Security Dashboard
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif