name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch: # Manual trigger for testing

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install OSV Scanner
        run: |
          curl -LO https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64
          chmod +x osv-scanner-linux-amd64
          sudo mv osv-scanner-linux-amd64 /usr/local/bin/osv-scanner
      
      - name: Run OSV Scanner
        run: |
          osv-scanner --lockfile=path/to/your/lockfile > osv-results.sarif
      
      - name: Upload OSV Report to Security Dashboard
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-results.sarif
          
  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run Semgrep Analysis
        run: |
          semgrep --config=p/java --output=semgrep-results.sarif --sarif .
      
      - name: Upload Semgrep Report to Security Dashboard
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
